### ISSUE TITLE
拖更是不好的

### ISSUE THREAD

**Issue by jiangxy** [jiangxy/react-antd-admin#1]
我要忏悔😓

最近工作事情实在很多，抽不出时间更新。。。
过了11.11应该好多了
不能挖坑不填啊

**Comment by chenjinhao** [comment]
大神，还记得我吗，上次问问题的那个。我因为是新入坑的，对一些基础不熟悉，我想问下InnerForm.js里面，例如<CheckboxGroup options={options} {...getFieldProps(field.key)}/>这个，

 {...getFieldProps(field.key)} 是从哪里读取的参数？因为我想塞默认值，在querySchema里面加了一个defaultValue想用上，但是不知道如何配置

**Comment by chenjinhao** [comment]
我在我的项目里面加上了insertSchema.js和updateSchema.js用来定制添加和更新的表单，原本表单用的dataSchema.js情况下，是根据dataType来判断显示类型，现在我添加了showType，dataType就不关联显示类型了，这样可以吗

**Comment by jiangxy** [comment]
准备搞redux
