### ISSUE TITLE
多个页面对应同一个侧边栏和面包屑？

### ISSUE THREAD

**Issue by dlyt** [jiangxy/react-antd-admin#10]
比如说一个列表页，我点击进入详情页，但侧边栏和面包屑都不需要变化。我不知道目前能实现这个功能不。
我是这么实现的在menu.js中将key设置成数组
```js
key: ['alone', 'detail']
```
然后在遍历的时候处理一下，但是我遇到了一个问题，在Sidebar中改变items后，再从Breadcrumb中取出的sidebarMenu跟改变后的一样。
可以明明是从menu.js中取出来的啊，我改Sidebar为什么会影响到menu.js呢？

**Comment by jiangxy** [comment]
理论上是可以做到的，面包屑的显示请参考[Breadcrumb](https://github.com/jiangxy/react-antd-admin/blob/master/src/components/Breadcrumb/index.js)类，可以自己控制，针对不同的路径显示同样的面包屑是可以的

你说的“在Sidebar中改变items后，再从Breadcrumb中取出的sidebarMenu跟改变后的一样”，应该是因为修改的是同一个对象吧，可以google下“传值 vs 传引用”的区别

话说我觉得列表页->详情这种需求，更适合用modal实现。。。

**Comment by dlyt** [comment]
针对不同的路径显示同样的面包屑是可以的。
但是必须在侧边栏上要显示个栏目，我的意思是不改变侧边栏的情况下改变面包屑，代码了应该是在配置文件里绑定在一起，这个倒不用纠结。
第二个问题我是把items改变后又还原了，理论上应该能在导出的时候处理，让它在外面修改不影响里面。
总之，3Q

**Comment by jiangxy** [comment]
我新增了一个功能，针对单条记录可以自定义弹出的modal，可以看看
也许可以解决你 列表->详情 这种需求
