### ISSUE TITLE
如何实现菜单的级联

### ISSUE THREAD

**Issue by basebase** [jiangxy/react-antd-admin#11]
Hi，你好，再次打扰你...
我想问一下如何实现下拉框的级联选择，不是官网的效果。
例如：我选择北京，然后第二个下拉框出现海淀，西城等

**Comment by jiangxy** [comment]
这个。。目前还不支持级联
我以后加一种showType吧
如果要自己实现，可以参考：https://ant.design/components/cascader-cn/

**Comment by jiangxy** [comment]
我是不是理解错你的意思了
感觉你要的不是[Cascader](https://ant.design/components/cascader-cn/)的效果。。。

**Comment by basebase** [comment]
对，一开始要的不是这种效果。但是后来自己也不会写前端就先用着了。

**Comment by jiangxy** [comment]
额😓   我已经加了Cascader的效果   你可以参考下。。
那这个issue暂时关掉了
