### ISSUE TITLE
我喜欢你这样的中文注释

### ISSUE THREAD

**Issue by qwerasdfzxvv** [jiangxy/react-antd-admin#12]
作为一个运维人员想做点开发的东西，重要学的是思想。
所以我特别喜欢的这种中文注释，清楚，明白，关键还漂亮。
总而言之，言而总之，我love it

**Comment by jiangxy** [comment]
哈哈   谢谢喜欢我的絮絮叨叨😄
注释一方面是希望看代码时觉得“有趣”一点，另一方面也是怕自己以后会忘。。。
