### ISSUE TITLE
src: url('../../icon/iconfont.eot?t=1493863686309');

### ISSUE THREAD

**Issue by yanghong1105** [jiangxy/react-antd-admin#16]
为什么在index.less里面不支持这种格式，我应该怎么改，是不是因为这块的配置问题
test: /\.less$/,
        loader: 'style!css!' + `less?{"sourceMap":true,"modifyVars":${JSON.stringify(lessLoaderVars)}}`,  // 用!去链式调用loader

**Comment by jiangxy** [comment]
我测试是可以的    检查下文件路径是否正确？    必须是相对于当前less文件的路径

**Comment by yanghong1105** [comment]
谢谢您，谢谢您
