### ISSUE TITLE
公司有自己的后台，我想套用一下这套模板，怎么和自己公司的后台连接呢

### ISSUE THREAD

**Issue by yanghong1105** [jiangxy/react-antd-admin#19]

**Comment by sunchenguang** [comment]
看看`config.js`和`MockAjax.js`，还有文档，用这一套，接入后端也要花不少时间

**Comment by yanghong1105** [comment]
请问一下您上面的列表上的数据是从哪来的

**Comment by jiangxy** [comment]
不用改造已有的后台，只要提供新的http接口和这套页面对接
需要提供的接口文档见：https://github.com/jiangxy/react-antd-admin/blob/master/docs/Ajax.md
