### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by sunchenguang** [jiangxy/react-antd-admin#20]
项目思路很好，但是代码耦合太严重，没有良好的模块化组件化，特别是DBTable组件，过于复杂繁琐，一点也不清晰，不利于维护，想把它拆分好一点，都不好拆。
另外注释适当就行了，没见过这么多注释的。。

**Comment by jiangxy** [comment]
确实，DBTable耦合严重，而且有很多hack，现在要我去改估计也会有点费劲。。。
想做成通用的也要考虑很多逻辑，之前想着先实现功能，以后有精力再优化吧

至于注释，因为我对react/ant design都是边学边写的，所以总是会随手记一些心得之类的
熟练了就应该不会这么多了

**Comment by 282159468** [comment]
我倒觉得现在的注释很清晰、很详细
