### ISSUE TITLE
关于主从关系的CRUD页面设计

### ISSUE THREAD

**Issue by whyuan1976** [jiangxy/react-antd-admin#25]
请问主从关系的CRUD页面该如何设计？比如订单表和订单明细表的录入。谢谢

**Comment by jiangxy** [comment]
这个要看需求吧    如果没有复杂的交互    可以在table中最后的操作栏   加一个“跳转”链接
例子：[testAction.dataSchema.js](https://github.com/jiangxy/react-antd-admin/blob/master/src/schema/testAction.dataSchema.js#L94)
就类似于外键一样   跳到另外一个表的CRUD界面
但是如果交互比较复杂    就需要定制开发了。。。
