### ISSUE TITLE
down下来之后，运行出错

### ISSUE THREAD

**Issue by Always-OL** [jiangxy/react-antd-admin#27]
输入guest/guest出错，出现： invalid username or password, 请联系管理员

**Comment by jiangxy** [comment]
能提供更多信息么？直接登录[这个demo](http://jxy.me/react-antd-admin/#/)是正常的么？

**Comment by Always-OL** [comment]
昨天研究了一天，是我node没有更新到最新版本，还有几个模块没安装，导致出现了很多问题。现在还有一个问题就是一直在报“GET http://localhost:8000/sockjs-node/info?t=1495854522366 net::ERR_CONNECTION_REFUSED”，目前还在找错误。

**Comment by jiangxy** [comment]
这个sockjs的错误，应该是webpack-dev-server的
首先查看下命令行输出    确认webpack-dev-server是否正常启动了？
