### ISSUE TITLE
调试代码时，更改devtool配置，依然看不到源文件

### ISSUE THREAD

**Issue by fantaishao** [jiangxy/react-antd-admin#29]
尝试通过Chrome打断点来调试代码，更改了webpack.config.js里的配置文件

将  //devtool: 'eval-source-map',
 更改为  devtool: 'source-map',
但是在浏览器中F12看到的依然是编译后的文件
![image](https://cloud.githubusercontent.com/assets/13132833/26636623/f511e04e-464f-11e7-9e5c-d4779090711f.png)

**楼主在写项目的时候是通过什么途径来调试代码的？**

**Comment by jiangxy** [comment]
抱歉这其实是个配置错误😓，因为package.json中写死了`--devtool eval`，删掉这项就可以了
参考[这个commit](https://github.com/jiangxy/react-antd-admin/commit/71d4b6196d87adc33abac78e629d89259a597415)
我不怎么用chrome调试代码，所以一直也没发现这个问题。。。我一般会加不同级别的日志来调试

**Comment by fantaishao** [comment]
比较习惯 F12调试代码。
改了之后能正常调试了，感激！
