### ISSUE TITLE
菜单的动态显示

### ISSUE THREAD

**Issue by ToQuery** [jiangxy/react-antd-admin#31]
请问你如何实现菜单动态显示的。

目前我这的需求，后台返回菜单数据，前台根据返回的数据动态的显示，请问可以做到么？

**Comment by jiangxy** [comment]
你说的动态显示     指的是哪些动态呢？
目前能实现动态新增、减少输入项，下拉列表的动态内容之类的，参考[这个文档](https://github.com/jiangxy/react-antd-admin/blob/master/docs/AsyncSchema.md)
需要注意加载远程schema的时机，只有组件初始化时才会去请求后端的

如果你指的是组件初始化之后的动态，比如两个输入项的联动之类的，目前还不支持。。

**Comment by whyuan1976** [comment]
我刚改过：
Sidebar/index.js中
    const paths = [];  // 暂存各级路径, 当作stack用
    const level1KeySet = new Set();  // 暂存所有顶级菜单的key
    const level2KeyMap = new Map();  // 次级菜单与顶级菜单的对应关系
    const menus = items;    

最后一句改成 this.state.data或res.data;把整段处理改成一个函数，在api调用成功后，调用。
组件mount时候，调用api，取得res
全部解析完，修改state，刷新一下就可以。

**Comment by jiangxy** [comment]
是的   这样是可行的
我这边也会参考下   希望能做的更通用一点
