### ISSUE TITLE
IE11下，查询按钮按下出错

### ISSUE THREAD

**Issue by whyuan1976** [jiangxy/react-antd-admin#34]
Unhandled promise rejection TypeError: 调用的对象无效
SCRIPT65535: 调用的对象无效
throttleByAnimationFrame.js (35,13)。

**Comment by whyuan1976** [comment]
补充一点，dev环境有这个问题，prod正常。

**Comment by jiangxy** [comment]
估计是webpack dev server的问题，之前也碰到过在IE下webpack dev server的报错
似乎目前没啥好办法。。。可以试试升级下版本
