### ISSUE TITLE
CRUD模式修改

### ISSUE THREAD

**Issue by whyuan1976** [jiangxy/react-antd-admin#35]
现有模式是新增，编辑弹出窗口。但这种方式如果要跳转到编辑画面，就很难实现。
我们原来把一览页面，新增，编辑做成平级的，可以来回切换，入口根据传入值，判断显示哪个页面。
请问这样改，在这个系统要如何修改。

**Comment by jiangxy** [comment]
这种估计要大改了     需要把新增、更新都做成单独的组件
我见过类似的做法     比如通过url传入id，在同一个页面上更新不同的记录

可以参考下InnerTable的实现，把其中的modal都抠出来作为单独的组件。。。
然后点击按钮不是弹出modal，而是打开一个新窗口，需要传入表名和id

**Comment by whyuan1976** [comment]
我的想法是把查询，新增，更新做成一个控件，通过state控制哪个页面显示，哪个不显示，路由是同一个，只不过参数不同，这样是不是可行？

**Comment by whyuan1976** [comment]
我这边准备实施的解决方案是： crud还是使用原有设计。跳转的话，则在主画面显示，返回按钮可以回到crud模式。

代码实现：
DBTable:  index.js加入2个新状态 mode ，record
在跳转模式下，不显示Form和Page。
InnerTable.js中props传入状态，

    const jumpMode = (
      <div>
        <FormComponent ref={(input) => { this.formComponent = input; }} initData={this.formInitData}
          forUpdate={!this.state.modalInsert} keysToUpdate={this.keysToUpdate}/>
        <Row>
          <Col>
            <Button type="primary">确定</Button><Button>返回</Button>
          </Col>
        </Row>
      </div>
    );
    return (
      <div>
        { this.props.mode === 0 && crudMode}
        { this.props.mode === 1 && jumpMode}
      </div>
    );

这样改动，基本结构没有变化，只需要改一下细节就可以。
