### ISSUE TITLE
登陆成功后  不管在哪个页面点击浏览器自带的刷新按钮     都会回到登录页面  这个是有特殊的配置么 按说不该这样

### ISSUE THREAD

**Issue by FreemenL** [jiangxy/react-antd-admin#37]
登陆成功后  不管在哪个页面点击浏览器自带的刷新按钮     都会回到登录页面  这个是有特殊的配置么 按说不该这样

**Comment by jiangxy** [comment]
看下你的/getCurrentUser接口   是否正常  
这个接口必须返回当前的登录用户    否则会认为没有登录的

**Comment by whyuan1976** [comment]
debug模式下是这样的
