### ISSUE TITLE
报告一个小 bug：utils 里 date.format 中文显示问题

### ISSUE THREAD

**Issue by ywzhaiqi** [jiangxy/react-antd-admin#39]
原有

    var week = {
        "0": "/u65e5",
        "1": "/u4e00",
        "2": "/u4e8c",
        "3": "/u4e09",
        "4": "/u56db",
        "5": "/u4e94",
        "6": "/u516d"
    };

正确

    var week = {
        "0": "\u65e5",
        "1": "\u4e00",
        "2": "\u4e8c",
        "3": "\u4e09",
        "4": "\u56db",
        "5": "\u4e94",
        "6": "\u516d"
    };

后面的 `/u` 同上

**Comment by jiangxy** [comment]
谢谢提醒    这段代码我也忘记是从哪里抄来的了😓。。。我改改
不过自从antd的日期组件换成moment.js后，这个Date.format方法很少用到了
