### ISSUE TITLE
注销后地址不对，链接打不开

### ISSUE THREAD

**Issue by encorehe** [jiangxy/react-antd-admin#4]
你好，注销后地址不对 链接404  应该是退回到登录页面吧？

**Comment by jiangxy** [comment]
现在我对注销的处理，是直接`<a href=xxx />`跳转到某个地址的，见[Header组件](https://github.com/jiangxy/react-antd-admin/blob/master/src/components/Header/index.js)
跳转的地址可以在config.js中配置，如果配置不对确实会404的

本意是希望让服务端提供注销用的接口
后续的重定向之类的也由服务端控制
当然这个可以考虑优化下
