### ISSUE TITLE
DBTable配置成Tree Table自动展开属性不起作用。

### ISSUE THREAD

**Issue by whyuan1976** [jiangxy/react-antd-admin#40]
defaultExpandAllRows 不起作用。手工可以点开。试了一下，底层应该是可以的。

类似如下：
https://codepen.io/anon/pen/OgmVmR?editors=001

**Comment by jiangxy** [comment]
我试了下貌似是可以，直接改的InnerTable.js，代码类似这样：
```
<Table rowSelection={rowSelection} columns={this.tableSchema} dataSource={this.state.data} pagination={false}
               loading={tableLoading} expandedRowRender={record => <p>{'test'}</p>}
               defaultExpandedRowKeys={[1000, 1001]}/>
```
效果是这样：
![image](https://user-images.githubusercontent.com/1011123/27476952-3f2fc250-583d-11e7-9731-5158632e1963.png)

是不是defaultExpandAllRows的数据类型不对？如果写成`['1000', '1001']`是不会生效的

**Comment by whyuan1976** [comment]
谢谢楼主回答。我这边有2种场景，
1： 树形结构的数据（如组织关系的table），是通过data的children来维护结构的，这种模式需要默认展开所有的数据。问题反应的就是这种场景，还没有试过defaultExpandedRowKeys，不过就算可以，也十分不方便。
2：自定义展开，就是楼主的方式。我这里已经扩展了这部分功能，可以自定义展开内容（如table），不过精力有限，扩展的自定义组件的方式，非配置。


![image](https://user-images.githubusercontent.com/14135520/27505089-d744310c-58c9-11e7-881c-50ccaac389ad.png)

**Comment by ywzhaiqi** [comment]
这方面我是这么改的

在 `src\components\DBTable\InnerTable.js` 的 Table 里增加

    expandedRowRender={tableConfig.expandedRowRender}

然后在 schema config 里传入组件，类似这样（我这个是把 schema 中的 dataSchema、querySchema、config 合并在一起了）

    const NestedTable = (record) => {
      const columns = [
        { key: 'description', dataIndex: 'description', title: 'Description' },
      ]

      const data = [
        { key: record.id, ...record }
      ];

      return (
        <Table
          columns={columns}
          dataSource={data}
          pagination={false}
          size="middle"
          />
      )
    }

    export const config = {
      showExport: true,
      showImport: true,

      expandedRowRender: NestedTable,
    }

**Comment by ywzhaiqi** [comment]
InnerTable.js 里的 defaultExpandAllRows 加了？

**Comment by whyuan1976** [comment]
做test的时候，加过好像没起作用。新作一个页面，同样代码又是可以的。不知道DBTable里面有什么特殊操作吗？



1935326097@qq.com
 
发件人： ywzhaiqi
发送时间： 2017-06-24 13:38
收件人： jiangxy/react-antd-admin
抄送： whyuan1976; Author
主题： Re: [jiangxy/react-antd-admin] DBTable配置成Tree Table自动展开属性不起作用。 (#40)
InnerTable.js 里的 defaultExpandAllRows 加了？

**Comment by ywzhaiqi** [comment]
传递给 table 的 dataSource 的数据是筛选过的（结构如下），默认没有了 children

	{
		$$rawData： {}，
		id: 1,
		title: 'aaa'
	}

**Comment by ywzhaiqi** [comment]
@whyuan1976 
>这种方式默认不展开明细，展开按下，再加载远程数据。

你怎么加载远程数据的？`expandedRowRender` 不是只能是个函数吗？

**Comment by whyuan1976** [comment]
@ywzhaiqi 

树形结构的table（例如组织关系）是不需要2次加载的，这时希望能使用defaultExpandAllRows 全展开。按照指定key的方式，是可以展开的，就是太麻烦了。二次加载的table也做过，加载的数据需要按照展开的key做map保存。我偷懒展开一个就自动关闭其他的，只需要保存最新展开的data。

**Comment by ywzhaiqi** [comment]
@whyuan1976 
没懂，二次加载是在 `expandedRowRender` 函数里面的吗？这不是组件，没法设置 ajax 的返回值。

**Comment by whyuan1976** [comment]
二次加载是在onExpand里实现，二次加载这部分没问题。是一次性加载树形结构的数据，无法通过defaultExpandAllRows 属性默认展开所有节点。

**Comment by ywzhaiqi** [comment]
@whyuan1976 

原来是用 `onExpand`。谢谢解答。

你的这个问题是 antd  table 使用的问题。你的示例改成 componentDidMount 加载数据默认就不会展开了。
https://codepen.io/ywzhaiqi/pen/YQLNva

**Comment by whyuan1976** [comment]
@ywzhaiqi 
谢谢。好像是的，改成componentWillMount就没有问题。
