### ISSUE TITLE
重构DBTable组件

### ISSUE THREAD

**Issue by sunchenguang** [jiangxy/react-antd-admin#43]
采用React组件化的开发方式，简洁清晰的整理了InnerForm的实现，InnerTable类似。
https://github.com/sunchenguang/react-antd-admin/commit/72d89d61be531a95f59bd0d9858ea055b9415d4b

重点是`queryForm.js`, 通过拆分组件和逻辑，来让整个流程清晰。
希望这个思路能有帮助。

**Comment by ywzhaiqi** [comment]
支持，希望能组件化，可用于其它项目
