### ISSUE TITLE
注销问题求解

### ISSUE THREAD

**Issue by whyuan1976** [jiangxy/react-antd-admin#44]
登录后，使用token进行权限控制。注销的话，请问如果修改APP组件上的login状态。一层层往上回调？

**Comment by jiangxy** [comment]
抱歉没太明白这个注销的逻辑。。
但是login状态是保存在redux store中的，如果要清除这个状态，理论上来说要在注销的地方触发一个action，可以参考下Login组件中，登录成功的action是如何处理的
还有一种方法是从context中获取redux store然后直接修改状态，但这样做好像不太好

**Comment by whyuan1976** [comment]
好的，明白了。最近在忙其它的，有空试试。
