### ISSUE TITLE
Meteor Crud Integration

### ISSUE THREAD

**Issue by mortSoudain** [jiangxy/react-antd-admin#45]
Hi! I think your job with the CRUD and the tab behavior it's just awsome.

I'm using Meteor+React +Antd and it's really smooth, i'm doing my own cruds but didn't get to the point of abstraction for doing just one component to work with any collection, so i'm considering the possibility to integrate your job with Meteor.

Is there a simple way to archive this?

I would really appreciate your help.

PD: Sorry for my bad english, my native language it's spanish xd.
PD2: I imagine an integration with simple schema or something like that

**Comment by jiangxy** [comment]
Hi, I'm glad you like this project.😄

Sorry I'm not familiar with Meteor. This project is just an front-end interface, and you can put it on any backend platform(java, python, node, etc). You just have to provide HTTP APIs, and here is [the doc](https://github.com/jiangxy/react-antd-admin/blob/master/docs/Ajax.md). But this doc is written in Chinese, if you need I can provide English version, will take some time.

My core concept is that you can describe your table (to CRUD) with a "json schema file", like [this one](https://github.com/jiangxy/react-antd-admin/blob/master/src/schema/test.dataSchema.js). Then render different forms/tables according to the schema file.

Any questions/advices are welcome.

PD: Sorry for my bad english too...
