### ISSUE TITLE
热更新有点问题

### ISSUE THREAD

**Issue by Mathround** [jiangxy/react-antd-admin#46]

**Comment by Mathround** [comment]
里面修改一些页面内容，热更新一开始会正常更新，但多更改几次页面内容，热更新就不起作用了

**Comment by Mathround** [comment]
直到电脑重启项目重新跑起来热更新才起作用，不过后续又不起作用

**Comment by jiangxy** [comment]
热更新好像一直都有点问题，好像是react-hot-loader的锅，一直也没管它。。。
可以参考下这个issue：#38
