### ISSUE TITLE
我只想留下我自己的页面，剩下的大家知道在哪里可以去掉吗？

### ISSUE THREAD

**Issue by Mathround** [jiangxy/react-antd-admin#48]
整个页面我只想留下我自己开发的页面，开发完成后最后部署服务器，页面上无关的东西我想去掉，比如页面左侧栏以及页面顶端以及页尾这些内容，大家知道在哪里可以去掉吗？我不需要这些

**Comment by jiangxy** [comment]
如果有这种需求，可以把[App.js](https://github.com/jiangxy/react-antd-admin/blob/master/src/components/App/index.js#L300)中Sidebar、Footer、Header等组件都注释掉

**Comment by Mathround** [comment]
谢谢，找到了，还有个问题，怎么把登录页面去掉？？严重影响开发效率了
