### ISSUE TITLE
怎么把登录页面去掉？？严重影响开发效率了

### ISSUE THREAD

**Issue by Mathround** [jiangxy/react-antd-admin#49]
怎么把登录页面去掉呢？？严重影响开发效率了，我想直接跳转到我自己的页面，

**Comment by Mathround** [comment]
我知道在哪弄了，亲们不用回答了

**Comment by yinsang** [comment]
怎么去的

**Comment by Mathround** [comment]
路由页面里面，<Route path="/" component={Management}>  component里面改成自己的就行了，不过现在有个问题又来了，页面最底部跟我页面底部有个距离，这个距离不知道怎么去掉，坑

**Comment by Mathround** [comment]
<Provider store={store}>
    <Router history={hashHistory}>
      <Route path="/" component={Management}>

 component里面改成自己的就行了

**Comment by Mathround** [comment]
`<Provider store={store}>
    <Router history={hashHistory}>
      <Route path="/" component={Management}>
        <IndexRoute component={Management} />`

component里面改成自己的就行了

**Comment by yinsang** [comment]
.ant-layout-footer {
  height: 64px;
  line-height: 64px;
  text-align: center;
  font-size: 12px;
  color: #999;
  background: #fff;
  border-top: 1px solid #e9e9e9;
  width: 100%;
  position:fixed;
  bottom:0;
}

**Comment by yinsang** [comment]
在Footer 的less文件里，把样式给改了。

**Comment by Mathround** [comment]
这样弄不行呀，我都已经把Footer这个组件已经去掉了，在里面更改样式是不起作用的，要不加个微信吧， hero388，微信里面我们一起互相帮助下，我现在用这个脚手架开发项目，遇到好几个头疼的问题

**Comment by Mathround** [comment]
我代码问题  已经解决

**Comment by yinsang** [comment]
666

**Comment by yinsang** [comment]
你的微信不对啊，兄弟。那是个卖吉他的哥们。你加我吧
small-wolf-wolf

**Comment by Mathround** [comment]
兄弟 我也加不上你，输入你的微信号提示用户不存在
