### ISSUE TITLE
能否打开一个功能就是一个页签tab页呢？

### ISSUE THREAD

**Issue by ifcheung2012** [jiangxy/react-antd-admin#5]
如题

**Comment by jiangxy** [comment]
能详细描述下么？

**Comment by iamnotterminator** [comment]
hi, @jiangxy 
楼上说的应该是 每次点击一个菜单项时候 打开一个[Tabs](https://ant.design/components/tabs-cn/)选项卡.

另 这个项目对我有很大帮助,我现在自己优化了很多:
querySchema与dataSchema合并为一个文件,增加字段暂时不显示等自定义属性.
表的字段能自动识别为图片,html富文本 并加载相应组件处理.
但更改挺多 不知道怎么提交给你.

**Comment by jiangxy** [comment]
@ifcheung2012 
如果是需要[tabs组件](https://ant.design/components/tabs-cn/)，那这个组件是显示在哪里呢？面包屑导航之下么？那右侧就有三层导航了：header/面包屑/tab，会不会有点重复呢

@iamnotterminator 
很高兴能帮到你😄，欢迎贡献代码
你可以用[Pull Request](https://help.github.com/articles/about-pull-requests/)提交修改，我会去看情况合并的；也可以传到你自己的一个仓库里，让我参考你的实现也行。
不过我最近打算对DBTable组件大改一次，可能会和一些你的修改有冲突。。。
之前DBTable的实现效率比较差，代码也很丑。。。

**Comment by jiangxy** [comment]
@ifcheung2012    已经新增tab模式    可以参考下
https://github.com/jiangxy/react-antd-admin/releases

**Comment by sbyps** [comment]
tab模式下点击tab没有将路由切换至该tab对应的url和nav list中，这算个问题么

**Comment by jiangxy** [comment]
@sbyps 是个问题   但暂时没想好怎么解决  要去研究下react-router😓
对使用没影响的话    可以先忽略

**Comment by sbyps** [comment]
@jiangxy 还有个问题，我用npm run dev后webpack compile successfully，但是浏览器拒绝访问，我把webpack的配置换成官方的antd-demo的配置就可以了，不知道你能不能复现

**Comment by jiangxy** [comment]
@sbyps   这个倒没有碰到过    你是访问的`localhost:8080`么？  试着加个index.html试试？
而且我这边`npm run dev`并未看到有`webpack compile successfully`之类的字样
方便的话发下截图不

**Comment by sbyps** [comment]
@jiangxy 能给个qq么，另有些react学习方面的事情想请教您！

**Comment by jiangxy** [comment]
@sbyps   337341913    但是我不太常上qq😓   最好还是issue/邮件沟通

**Comment by yashi-david** [comment]
请问你们都运行成功了么，为什么我 npm run dev后会报错？

**Comment by jiangxy** [comment]
@yashi-david   啥错误   能截个图给我看看么？
另外   node/npm/还有系统版本     能都说一下么？

**Comment by yashi-david** [comment]
node 6.2.0 以及 npm 3.8.9 win10 系统   npm报错的语句

ERROR in ./src/utils/RealAjax.js
Module not found: Error: Cannot resolve module 'superagent' in D:\admin-cu\src\utils
 @ ./src/utils/RealAjax.js 17:18-39

**Comment by yashi-david** [comment]
我晕 被自己蠢哭了  我还没有npm install 它  我再试试
