### ISSUE TITLE
TBTable如何做数据导出

### ISSUE THREAD

**Issue by super-ai** [jiangxy/react-antd-admin#53]
如题

Demo也没看到效果

**Comment by jiangxy** [comment]
我这边的做法，是完全委托给后端的     
点击导出按钮后，会新开一个窗口访问`http://{host}/{tableName}/export?q=`，表单中的查询条件都会作为q参数传过去。相关逻辑见[handleExport](https://github.com/jiangxy/react-antd-admin/blob/master/src/components/DBTable/InnerForm.js#L163)方法。
这时后端一般要返回一个下载请求，类似这种：`res.setHeader("Content-Disposition", "attachment; filename=" + fileName);`

这种做法其实不太优雅，因为我之前不知道js怎么处理文件下载，后来了解到[FileSaver.js](https://github.com/eligrey/FileSaver.js/)，但一直都没改。。。
