### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by Demon2** [jiangxy/react-antd-admin#57]
~/p/react-antd-admin> npm run dev

> react-antd-admin@1.0.0 dev /Users/kz/projects/react-antd-admin
> webpack-dev-server --devtool eval --progress --colors --content-base dist --hot --inline --display-error-details

 70% 1/1 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/kz/.npm-global/bin/npm" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! react-antd-admin@1.0.0 dev: `webpack-dev-server --devtool eval --progress --colors --content-base dist --hot --inline --display-error-details`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-antd-admin@1.0.0 dev script 'webpack-dev-server --devtool eval --progress --colors --content-base dist --hot --inline --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-antd-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --devtool eval --progress --colors --content-base dist --hot --inline --display-error-details

**Comment by jiangxy** [comment]
从报错的信息看，好像是8080端口已经被占用了
修改[package.json](https://github.com/jiangxy/react-antd-admin/blob/master/package.json#L67)，加上`--port`参数，换个端口试试？

**Comment by luyv-atk** [comment]
npm错误缺少脚本：“dev”
npm error要查看脚本列表，请运行：
npm error npm run npm error此运行的完整日志可以在以下位置找到：C:\Users\4399\AppData\Local\npm cache\_logs\2024-11-11-11T21_29-42_389Z-debug-0.log
