### ISSUE TITLE
使用IDE问题

### ISSUE THREAD

**Issue by linjiazhen** [jiangxy/react-antd-admin#58]
请问您使用的是哪个IDE?
我使用ideallij Idea导入工程但是会有很多红色语法错误提示，有办法解决吗？

**Comment by jiangxy** [comment]
我使用的是webstorm，要开启ES6和react等特性
在Preferences -> Languages & Frameworks -> JavaScript中进行配置，具体的步骤有点忘了。。可以搜一下
