### ISSUE TITLE
npm run prod 报错

### ISSUE THREAD

**Issue by JustYJQ** [jiangxy/react-antd-admin#6]
> react-antd-admin@1.0.0 prod D:\2017ToDo\MyDo\React\react-antd-admin-master
> NODE_ENV=production webpack --progress --colors --config webpack.config.prod.js -p --display-error-details

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! react-antd-admin@1.0.0 prod: `NODE_ENV=production webpack --progress --colors --config webpack.config.prod.js -p --display-error-details`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-antd-admin@1.0.0 prod script 'NODE_ENV=production webpack --progress --colors --config webpack.config.prod.js -p --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-antd-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --progress --colors --config webpack.config.prod.js -p --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-antd-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-antd-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\2017ToDo\MyDo\React\react-antd-admin-master\npm-debug.log

**Comment by jiangxy** [comment]
在windows下使用是会有点问题的   之前没考虑到
应该已经修复了    重新拉下代码再试试？
