### ISSUE TITLE
API 有四个的情况下怎么处理？

### ISSUE THREAD

**Issue by luoxiaofeng369** [jiangxy/react-antd-admin#62]
项目中需要用到四个API  ，想知道怎么配置     也就是有四个地址

**Comment by jiangxy** [comment]
这个意思是说，有4个表的CRUD？   每个表的CRUD接口对应着不同的地址？
暂时无解。。。目前没有考虑过这种情况。

**Comment by luoxiaofeng369** [comment]
我是在webpack.config.js配置文件 写了代理 

devServer: {
    proxy: {
      "/h-test1":{target:"http://localhost:8081"},
      "/h-test2":{target:"http://localhost:8082"}
}

发现这种方法可以实现需求
