### ISSUE TITLE
使用webstorm打开项目，全是ESLint的警告

### ISSUE THREAD

**Issue by zjiecode** [jiangxy/react-antd-admin#69]
你好，我打开工程，全是ESLint的警告，是不是配置的问题呢？之前没有配置过ESLint，感谢。
![image](https://user-images.githubusercontent.com/38341983/42672903-445d3d4c-869b-11e8-8a20-72bcd33dd158.png)

**Comment by jiangxy** [comment]
不好意思    我也挺久没写ES了
在webstorm的Preferences中搜下eslint试试？

**Comment by zjiecode** [comment]
谢谢。
