### ISSUE TITLE
能否多页签显示内容

### ISSUE THREAD

**Issue by fanjialing** [jiangxy/react-antd-admin#7]
意思是点击左边菜单的时候,右边显示的内容是一个页签,在点个菜单,又出来一个页签..
你现在点了菜单后 会把你上一次的内容替换掉...不知道我描述得你能懂否....语言组织
不是很好。。。

**Comment by jiangxy** [comment]
哦   我明白你的意思了   我考虑下😄

**Comment by jiangxy** [comment]
这个issue和 #5  是同样的
暂时关闭

**Comment by jiangxy** [comment]
@fanjialing   我新增了一个tab模式    可以参考下
https://github.com/jiangxy/react-antd-admin/releases
