### ISSUE TITLE
我想修改结构后table字段的间距

### ISSUE THREAD

**Issue by basebase** [jiangxy/react-antd-admin#8]
你好，我想修改结构后table字段的间距。
字段少的时候，间距太大，请问是在哪里修改？
谢谢！

**Comment by jiangxy** [comment]
参考我的[这个commit](https://github.com/jiangxy/react-antd-admin/commit/83e217b5ef10a990ae7ede7b0a7aaed02d8d271d)，在dataSchema里新增了一个属性width，可以设置每列的宽度 

其实关于表格还有很多可以设置的，参考[antd的文档](https://ant.design/components/table-cn/#Column)

**Comment by basebase** [comment]
@jiangxy 恩，多谢。中午的时候解决了。不过没写的你这么灵活，学习了。
